#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = 
CFLAGS = -Wall -fexceptions -DENABLE_DOWNLOAD
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = 

INC_DEBUG = $(INC)
CFLAGS_DEBUG = $(CFLAGS) -std=c++11 -Wall -g
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)-lssh -lprotobuf -lcrypto -lssl -lircclient
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/RetroShareChatBot

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -O2 -std=c++11
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)-lssh -lprotobuf -lcrypto -lssl -lircclient
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = bin/Release/RetroShareChatBot

OBJ_DEBUG = $(OBJDIR_DEBUG)/src/main.o $(OBJDIR_DEBUG)/src/gencc/system.pb.o $(OBJDIR_DEBUG)/src/gencc/stream.pb.o $(OBJDIR_DEBUG)/src/gencc/search.pb.o $(OBJDIR_DEBUG)/src/gencc/peers.pb.o $(OBJDIR_DEBUG)/src/gencc/files.pb.o $(OBJDIR_DEBUG)/src/gencc/core.pb.o $(OBJDIR_DEBUG)/src/AutoResponse.o $(OBJDIR_DEBUG)/src/gencc/chat.pb.o $(OBJDIR_DEBUG)/src/SSHConnector.o $(OBJDIR_DEBUG)/src/RetroShareRPC.o $(OBJDIR_DEBUG)/src/RetroShareChat.o $(OBJDIR_DEBUG)/src/ProtoBuf.o $(OBJDIR_DEBUG)/src/IRC.o $(OBJDIR_DEBUG)/src/ConfigHandler.o $(OBJDIR_DEBUG)/src/ChatBot.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/src/main.o $(OBJDIR_RELEASE)/src/gencc/system.pb.o $(OBJDIR_RELEASE)/src/gencc/stream.pb.o $(OBJDIR_RELEASE)/src/gencc/search.pb.o $(OBJDIR_RELEASE)/src/gencc/peers.pb.o $(OBJDIR_RELEASE)/src/gencc/files.pb.o $(OBJDIR_RELEASE)/src/gencc/core.pb.o $(OBJDIR_RELEASE)/src/AutoResponse.o $(OBJDIR_RELEASE)/src/gencc/chat.pb.o $(OBJDIR_RELEASE)/src/SSHConnector.o $(OBJDIR_RELEASE)/src/RetroShareRPC.o $(OBJDIR_RELEASE)/src/RetroShareChat.o $(OBJDIR_RELEASE)/src/ProtoBuf.o $(OBJDIR_RELEASE)/src/IRC.o $(OBJDIR_RELEASE)/src/ConfigHandler.o $(OBJDIR_RELEASE)/src/ChatBot.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG)/src || mkdir -p $(OBJDIR_DEBUG)/src
	test -d $(OBJDIR_DEBUG)/src/gencc || mkdir -p $(OBJDIR_DEBUG)/src/gencc

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/src/main.o: src/main.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/main.cpp -o $(OBJDIR_DEBUG)/src/main.o

$(OBJDIR_DEBUG)/src/gencc/system.pb.o: src/gencc/system.pb.cc
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/gencc/system.pb.cc -o $(OBJDIR_DEBUG)/src/gencc/system.pb.o

$(OBJDIR_DEBUG)/src/gencc/stream.pb.o: src/gencc/stream.pb.cc
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/gencc/stream.pb.cc -o $(OBJDIR_DEBUG)/src/gencc/stream.pb.o

$(OBJDIR_DEBUG)/src/gencc/search.pb.o: src/gencc/search.pb.cc
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/gencc/search.pb.cc -o $(OBJDIR_DEBUG)/src/gencc/search.pb.o

$(OBJDIR_DEBUG)/src/gencc/peers.pb.o: src/gencc/peers.pb.cc
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/gencc/peers.pb.cc -o $(OBJDIR_DEBUG)/src/gencc/peers.pb.o

$(OBJDIR_DEBUG)/src/gencc/files.pb.o: src/gencc/files.pb.cc
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/gencc/files.pb.cc -o $(OBJDIR_DEBUG)/src/gencc/files.pb.o

$(OBJDIR_DEBUG)/src/gencc/core.pb.o: src/gencc/core.pb.cc
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/gencc/core.pb.cc -o $(OBJDIR_DEBUG)/src/gencc/core.pb.o

$(OBJDIR_DEBUG)/src/AutoResponse.o: src/AutoResponse.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/AutoResponse.cpp -o $(OBJDIR_DEBUG)/src/AutoResponse.o

$(OBJDIR_DEBUG)/src/gencc/chat.pb.o: src/gencc/chat.pb.cc
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/gencc/chat.pb.cc -o $(OBJDIR_DEBUG)/src/gencc/chat.pb.o

$(OBJDIR_DEBUG)/src/SSHConnector.o: src/SSHConnector.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/SSHConnector.cpp -o $(OBJDIR_DEBUG)/src/SSHConnector.o

$(OBJDIR_DEBUG)/src/RetroShareRPC.o: src/RetroShareRPC.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/RetroShareRPC.cpp -o $(OBJDIR_DEBUG)/src/RetroShareRPC.o

$(OBJDIR_DEBUG)/src/RetroShareChat.o: src/RetroShareChat.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/RetroShareChat.cpp -o $(OBJDIR_DEBUG)/src/RetroShareChat.o

$(OBJDIR_DEBUG)/src/ProtoBuf.o: src/ProtoBuf.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/ProtoBuf.cpp -o $(OBJDIR_DEBUG)/src/ProtoBuf.o

$(OBJDIR_DEBUG)/src/IRC.o: src/IRC.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/IRC.cpp -o $(OBJDIR_DEBUG)/src/IRC.o

$(OBJDIR_DEBUG)/src/ConfigHandler.o: src/ConfigHandler.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/ConfigHandler.cpp -o $(OBJDIR_DEBUG)/src/ConfigHandler.o

$(OBJDIR_DEBUG)/src/ChatBot.o: src/ChatBot.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/ChatBot.cpp -o $(OBJDIR_DEBUG)/src/ChatBot.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)/src
	rm -rf $(OBJDIR_DEBUG)/src/gencc

before_release: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE)/src || mkdir -p $(OBJDIR_RELEASE)/src
	test -d $(OBJDIR_RELEASE)/src/gencc || mkdir -p $(OBJDIR_RELEASE)/src/gencc

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/src/main.o: src/main.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/main.cpp -o $(OBJDIR_RELEASE)/src/main.o

$(OBJDIR_RELEASE)/src/gencc/system.pb.o: src/gencc/system.pb.cc
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/gencc/system.pb.cc -o $(OBJDIR_RELEASE)/src/gencc/system.pb.o

$(OBJDIR_RELEASE)/src/gencc/stream.pb.o: src/gencc/stream.pb.cc
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/gencc/stream.pb.cc -o $(OBJDIR_RELEASE)/src/gencc/stream.pb.o

$(OBJDIR_RELEASE)/src/gencc/search.pb.o: src/gencc/search.pb.cc
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/gencc/search.pb.cc -o $(OBJDIR_RELEASE)/src/gencc/search.pb.o

$(OBJDIR_RELEASE)/src/gencc/peers.pb.o: src/gencc/peers.pb.cc
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/gencc/peers.pb.cc -o $(OBJDIR_RELEASE)/src/gencc/peers.pb.o

$(OBJDIR_RELEASE)/src/gencc/files.pb.o: src/gencc/files.pb.cc
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/gencc/files.pb.cc -o $(OBJDIR_RELEASE)/src/gencc/files.pb.o

$(OBJDIR_RELEASE)/src/gencc/core.pb.o: src/gencc/core.pb.cc
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/gencc/core.pb.cc -o $(OBJDIR_RELEASE)/src/gencc/core.pb.o

$(OBJDIR_RELEASE)/src/AutoResponse.o: src/AutoResponse.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/AutoResponse.cpp -o $(OBJDIR_RELEASE)/src/AutoResponse.o

$(OBJDIR_RELEASE)/src/gencc/chat.pb.o: src/gencc/chat.pb.cc
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/gencc/chat.pb.cc -o $(OBJDIR_RELEASE)/src/gencc/chat.pb.o

$(OBJDIR_RELEASE)/src/SSHConnector.o: src/SSHConnector.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/SSHConnector.cpp -o $(OBJDIR_RELEASE)/src/SSHConnector.o

$(OBJDIR_RELEASE)/src/RetroShareRPC.o: src/RetroShareRPC.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/RetroShareRPC.cpp -o $(OBJDIR_RELEASE)/src/RetroShareRPC.o

$(OBJDIR_RELEASE)/src/RetroShareChat.o: src/RetroShareChat.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/RetroShareChat.cpp -o $(OBJDIR_RELEASE)/src/RetroShareChat.o

$(OBJDIR_RELEASE)/src/ProtoBuf.o: src/ProtoBuf.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/ProtoBuf.cpp -o $(OBJDIR_RELEASE)/src/ProtoBuf.o

$(OBJDIR_RELEASE)/src/IRC.o: src/IRC.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/IRC.cpp -o $(OBJDIR_RELEASE)/src/IRC.o

$(OBJDIR_RELEASE)/src/ConfigHandler.o: src/ConfigHandler.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/ConfigHandler.cpp -o $(OBJDIR_RELEASE)/src/ConfigHandler.o

$(OBJDIR_RELEASE)/src/ChatBot.o: src/ChatBot.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/ChatBot.cpp -o $(OBJDIR_RELEASE)/src/ChatBot.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)/src
	rm -rf $(OBJDIR_RELEASE)/src/gencc

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

